PR-005_CSS & Home & Member
WildCodeSchool/rogue-one-mvc pull request #26
Opened 2024-02-01 16:29 UTC by joelmayemba

+ homepage update ans css
+ Global css uupdate
+ Members page update

2024-02-02 10:05 UTC, Benja-san requested changes

2024-02-02 10:23 UTC, joelmayemba commented on src/View/Home/index.html.twig
> +						<div class="header-text">
done

2024-02-02 11:12 UTC, chouaibj approved these changes

2024-02-07 14:59 UTC, joelmayemba commented on src/View/Home/index.html.twig
Done

2024-02-07 15:00 UTC, joelmayemba commented on src/View/Members/index.html.twig
Done

2024-02-08 09:46 UTC, Benja-san commented on src/View/Home/index.html.twig
> +								{# <span class="category">Cocktails
remove dead code

2024-02-08 15:48 UTC, Benja-san approved these changes

2024-02-08 15:49 UTC, merged