member page
WildCodeSchool/rogue-one-mvc pull request #29
Opened 2024-02-02 11:20 UTC by joelmayemba

Add dev members

2024-02-02 11:29 UTC, chouaibj approved these changes

2024-02-07 14:02 UTC, Benja-san requested changes

2024-02-07 14:02 UTC, Benja-san commented on src/Model/MembersManager.php
> +    public function selectAllMembers(): array
if your method only call the parent method selectAll, you can suppress it and directly use the selectAll method when needed in controllers

2024-02-07 14:02 UTC, Benja-san commented on src/View/Members/index.html.twig
No H1 on this page

2024-02-07 15:41 UTC, joelmayemba commented on src/View/Members/index.html.twig
Done

2024-02-07 15:42 UTC, joelmayemba commented on src/Model/MembersManager.php
> +    public function selectAllMembers(): array
Done

2024-02-08 09:54 UTC, Benja-san requested changes
Remove all useless methods in managers (selectAllMembers is not used anymore) (getMocktailById only referes to its parent method so it can be erased in favor of selectOneById from abstract model) (and so on...)

2024-02-08 16:17 UTC, Benja-san approved these changes

2024-02-08 16:21 UTC, merged