37 css responsive
WildCodeSchool/rogue-one-mvc pull request #39
Opened 2024-02-06 16:22 UTC by joelmayemba

Navbar update with an active on a href + responsive page for contact

2024-02-07 14:05 UTC, Benja-san requested changes

2024-02-07 14:05 UTC, Benja-san commented on public/assets/js/navbar.js
replace var by const or let

2024-02-07 14:08 UTC, joelmayemba commented on public/assets/js/navbar.js
Done

2024-02-07 16:10 UTC, chouaibj approved these changes

2024-02-08 09:49 UTC, Benja-san requested changes

2024-02-08 09:49 UTC, Benja-san commented on src/View/Mocktails/index.html.twig
add H1 to pages when they need referencing

2024-02-08 10:15 UTC, Benja-san requested changes
Why did you change let into var ?

2024-02-08 16:25 UTC, Benja-san approved these changes

2024-02-08 16:26 UTC, merged