PR__001__MVC & Twig
WildCodeSchool/rogue-one-mvc pull request #9
Opened 2024-01-25 08:46 UTC by joelmayemba

[--fix]
- Correction, modification et séparation du CSS;
- Ajout des pages MVC (Home, Mocktails, Contact et About);
- Création de la BDD ;
- Suppression des dossiers/fichiers encombrants de jquery/bootstrap, et ajout externe des liens bootstrap;

[in progress]
- page details mocktails;
- page contact (messagerie) ;
- page admin pour la gestion des produits (Mocktails -> SP2) ;
- Version mobile ;

2024-01-26 08:49 UTC, Benja-san requested changes

2024-01-26 08:49 UTC, Benja-san commented on database.sql
> +  ID INT AUTO_INCREMENT,
not null required

2024-01-26 08:49 UTC, Benja-san commented on database.sql
> +  `NAME` VARCHAR(25) NULL,
not null required

2024-01-26 08:49 UTC, Benja-san commented on database.sql
> +  `DESCRIPTION` VARCHAR(255) NULL,
can it be null ?

2024-01-26 08:49 UTC, Benja-san commented on database.sql
> +  `LINK` TEXT(255) NULL,
can it be null ?

2024-01-26 08:49 UTC, Benja-san commented on database.sql
> +CREATE TABLE IF NOT EXISTS `CATEGORY` (
See the commentaries above (for the first table) in order to apply it to every tables of your sql

2024-01-26 08:49 UTC, Benja-san commented on oldcode.txt
> +{% extends 'layout.html.twig' %}
remove useless and old code

2024-01-26 08:49 UTC, Benja-san commented on public/assets/css/mocktails copy.css
> +/* .mocktails .main-button:hover {
remove dead code

2024-01-26 08:49 UTC, Benja-san commented on public/assets/css/mocktails copy.css
> +/* .mocktails ul.mocktails-filter li a.is_active:hover {
remove dead code

2024-01-26 08:49 UTC, Benja-san commented on public/assets/js/mocktails.js
> +    var categories = document.querySelectorAll("#categories a");
const or let but never var

2024-01-26 08:49 UTC, Benja-san commented on public/assets/js/mocktails.js
> +    var mocktails = document.querySelectorAll(".mocktails-items");
const or let but never var

2024-01-26 08:49 UTC, Benja-san commented on public/assets/js/page-test.js
> +document.addEventListener("DOMContentLoaded", function () {
page test ? tests should be in gitignore or deleted ?

2024-01-26 08:49 UTC, Benja-san commented on src/Controller/MocktailDetailController.php
> +<?php
MocktailController should have a method index and show, no need to recreate an other controller since the MocktailController is already present and handle all the mocktail logic

2024-01-26 08:49 UTC, Benja-san commented on src/Controller/MocktailDetailController.php
> +        $mocktail = $mocktails[$product] ?? null;
you should create a method in your manager to retrieve only one product. Abstract controller already provides you this see selectOneById

2024-01-26 08:49 UTC, Benja-san commented on src/Model/Connection.php
you already have a connection with the abastract controller

2024-01-26 08:49 UTC, Benja-san commented on src/Model/MocktailDetailModel.php
> +<?php
remove useless file

2024-01-26 08:49 UTC, Benja-san commented on src/Model/MocktailsModel.php
> +    public static function getMocktailsData(): array
abstract controller already provides you a method to fetch everything from a table

2024-01-26 08:49 UTC, Benja-san commented on src/Model/MocktailsModel.php
> +    public static function getCategories(): array
create a CategoryManager

2024-01-26 08:49 UTC, Benja-san commented on src/Model/MocktailsModel.php
> +<?php
name of file should be MocktailManager

2024-01-26 08:49 UTC, Benja-san commented on src/View/About/index.html.twig
> +	<head>
no head tag in content block

2024-01-26 08:49 UTC, Benja-san commented on src/View/About/index.html.twig
> +	<div class="page-heading header-text">
think aboput main tag and relevant tag names for referencing app

2024-01-26 08:49 UTC, Benja-san commented on src/View/About/index.html.twig
> +						<h6>| À propos de nous</h6>
h6 ???

2024-01-26 08:49 UTC, Benja-san commented on src/View/Contact/index.html.twig
> +	<head>
no head tag in content block

2024-01-26 08:49 UTC, Benja-san commented on src/View/Contact/index.html.twig
> +	<div class="page-heading header-text">
same commentary than the about.html.twig file

2024-01-26 08:49 UTC, Benja-san commented on src/View/Home/index.html.twig
> +	<head>
no head tag in content block

2024-01-26 08:49 UTC, Benja-san commented on src/View/Home/index.html.twig
> +	<body>
no body in content block

2024-01-26 08:49 UTC, Benja-san commented on src/View/Home/index.html.twig
> +		<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
see commentary in your about/index.twig.html file

2024-01-26 08:49 UTC, Benja-san commented on src/View/Home/index.html.twig
> +		{#
remove dead code

2024-01-26 08:49 UTC, Benja-san commented on src/View/MocktailDetail/index.html.twig
> +{% extends 'layout.html.twig' %}
look at the other comments in the html twig files and apply 'em to this one

2024-01-26 08:49 UTC, Benja-san commented on src/View/Mocktails/index.html copy.twig
> +{% extends 'layout.html.twig' %}
look at the other comments in the html twig files and apply 'em to this one

2024-01-26 08:49 UTC, Benja-san commented on src/View/Mocktails/index.html.twig
> +
look at the other comments in the html twig files and apply 'em to this one

2024-01-26 08:49 UTC, Benja-san commented on src/routes.php
> +    // '' => ['HomeController', 'index',],
remove dead code

2024-01-26 08:58 UTC, joelmayemba commented on database.sql
> +  `NAME` VARCHAR(25) NULL,
Done

2024-01-26 09:00 UTC, joelmayemba commented on database.sql
> +  ID INT AUTO_INCREMENT,
Done

2024-01-26 09:01 UTC, joelmayemba commented on database.sql
> +  `LINK` TEXT(255) NULL,
Done

2024-01-26 09:02 UTC, joelmayemba commented on database.sql
> +  `DESCRIPTION` VARCHAR(255) NULL,
Done

2024-01-26 09:03 UTC, joelmayemba commented on database.sql
> +CREATE TABLE IF NOT EXISTS `CATEGORY` (
Done

2024-01-26 11:32 UTC, KevinGIRAULT approved these changes

2024-01-26 11:32 UTC, chouaibj approved these changes
still some syntaxes to fix, at least the code work

2024-01-29 14:32 UTC, Benja-san requested changes

2024-01-29 14:32 UTC, Benja-san commented on database.sql
> +INSERT INTO INGREDIENTS (ID, NAME) VALUES
Since your ID is auto incrmeent yopu don't need to specify it, just add the values

2024-01-29 14:32 UTC, Benja-san commented on database.sql
> +INSERT INTO MEMBER (NAME, DESCRIPTION, LINK) VALUES
3 values for 1 data ?

2024-01-29 14:32 UTC, Benja-san commented on database.sql
Id should always be NOT NULL
Members name, description should not be NULL
Category NAME should not be NULL
Product NAME, PRICE, details (at least) should NOT be NULL

2024-01-29 14:32 UTC, Benja-san commented on src/Controller/AdminController.php
>  class HomeController extends AbstractController
AdminController cannot have Homecontroller as a classname, and it should not lead to the homepage

2024-01-29 14:32 UTC, Benja-san commented on src/Controller/MocktailsController.php
>      public function mocktails(): string
this looks more like an index page to me than the one you named below : index is listing all products and categories.

2024-01-29 14:32 UTC, Benja-san commented on src/Controller/MocktailsController.php
> +    public function index(): string
why having an index not showing anything in your mocktail controller ?

2024-01-29 14:32 UTC, Benja-san commented on src/Model/CategoriesManager.php
> +        $formattedCategories = [];
why do you changes key values ?

2024-01-29 14:32 UTC, Benja-san commented on src/View/About/index.html.twig
> +{% extends 'layout.html.twig' %} {% block content %}
why would you wrap all the blocks into the content block ? look at the lc or repositories for more info

2024-01-29 14:32 UTC, Benja-san commented on src/View/Contact/index.html.twig
> +{% extends 'layout.html.twig' %} {% block content %}
why would you wrap all the blocks into the content block ? look at the lc or repositories for more info

2024-01-29 14:32 UTC, Benja-san commented on src/View/Home/index.html.twig
> +{% extends 'layout.html.twig' %} {% block content %}
why would you wrap all the blocks into the content block ? look at the lc or repositories for more info

2024-01-29 14:32 UTC, Benja-san commented on src/View/MocktailDetail/index.html.twig
change this file and its location to View/Mocktail/show.html.twig

2024-01-29 14:32 UTC, Benja-san commented on src/View/MocktailDetail/index.html.twig
> +{% extends 'layout.html.twig' %}{% block content %}
why would you wrap all the blocks into the content block ? look at the lc or repositories for more info

2024-01-29 14:32 UTC, Benja-san commented on src/View/layout.html.twig
>  		{% block nav %}
if you have a footer component, why don't you put this into a header component ?

2024-01-29 14:55 UTC, joelmayemba commented on database.sql
> +INSERT INTO INGREDIENTS (ID, NAME) VALUES
Done

2024-01-29 15:09 UTC, joelmayemba commented on database.sql
> +INSERT INTO MEMBER (NAME, DESCRIPTION, LINK) VALUES
Done

2024-01-29 15:52 UTC, joelmayemba commented on src/View/Home/index.html.twig
> +{% extends 'layout.html.twig' %} {% block content %}
done

2024-01-31 15:26 UTC, chouaibj commented
everything is fixed

2024-01-31 16:13 UTC, merged